services:
  # cypress:
  #   build:
  #     context: ./frontend/cypress
  #   depends_on:
  #     frontend:
  #       condition: service_started

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - todonet_pipeline
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - todonet_pipeline
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: tododb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      # “Monte o volume postgres_data no caminho /var/lib/postgresql/data do container”.
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todonet_pipeline
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tododb"]
      interval: 10s
      timeout: 5s
      retries: 5

# Permitir persistência de dados após reinicializações.
volumes:
  postgres_data:

networks:
  todonet_pipeline:
